name: AI Code Review
on:
    pull_request:
	 types: [opened, synchronize, reopened]  
     branches: ["main"]
permissions:
    contents: read
    pull-requests: write
    issues: write
    
jobs:
   ai_review:
        runs-on:  ubuntu-latest
        steps: 
        - name: Checkout repo
	      uses: actions/checkout@v3
        - name: Extract PR diff
          run: |
            git fetch origin ${{github.base_ref}}
            git diff origin/${{github.base_ref}}... > diff.txt
        - name: Set up Python
          uses: actions/setup-python@v4
	      with:
            python-verson:'3.11'
        - name: Install dependencies
	      run: pip install -r requirements.txt
        - name: Run AI Code Review
		  env:
			GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            PR_NUMBER: ${{github.event.pull_request.number}}
            REPO_FULL: ${{github.repository}}
            COMMIT_SHA: ${{github.event.pull_request.head.sha}}
		  run: python scripts/ai_review.py diff.txt
         